# This is a basic workflow that is manually triggered

name: Build Ubuntu-20 Images

# Manually triggered
on:
  workflow_dispatch:
    # No input required

jobs:
  build_base:
    runs-on: ubuntu-latest
    name: Builds base docker image
    env:
      REPO: axom/compilers
      IMAGE_OS: ubuntu-20
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Get dockerfile name
      shell: bash
      run: echo "##[set-output name=filename;]$(echo ${IMAGE_OS}/base/Dockerfile)"
      id: dockerfile_name
    - name: Get dockerhub repo name
      shell: bash
      run: |
        echo ${REPO}:${IMAGE_OS}_base_`date "+%m-%d-%y_%Hh-%Mm"`
        echo "##[set-output name=repo_plus_tag;]$(echo ${REPO}:${IMAGE_OS}_base_`date "+%m-%d-%y_%Hh-%Mm"`)"
        echo "##[set-output name=repo_plus_latest;]$(echo ${REPO}:${IMAGE_OS}_base_latest)"
      id: repo_name

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.repo_name.outputs.repo_plus_tag }},${{ steps.repo_name.outputs.repo_plus_latest }}
        file: ${{ steps.dockerfile_name.outputs.filename }}
        context: .
        platforms: linux/amd64
        build-args: branch=${{ steps.extract_branch.outputs.branch }}
